engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/LineLength:
        enabled: false
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
exclude_paths:
  - db/
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/vendor/"
