engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  flog:
    enabled: true
  reek:
    enabled: true
exclude_paths:
  - db/
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/vendor/"
