language: ruby
bundler_args: --without production
cache: bundler

rvm:
  - 2.4.2

addons:
  postgresql: "9.6"

env:
  global:
    - CC_TEST_REPORTER_ID=bebc502e26ccffa9458c107b85c89786238d7e657b97a1d5f8e343d9246c0c33

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - COVERAGE=on bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
