company_name: Santander
site_url: http://canseidosantander.herokuapp.com
site_title: Cansei do atendimento do Santander
brief_explanation: O Santander já nos fez perder dezenas de horas das nossas vidas com seu péssimo serviço e atendimento. Juntos vamos tentar mudar essa situação!
tweet_messages:
  - '@santander_br venho por meio deste tweet mostrar minha insatisfação com o serviço prestado por vocês'
  - '@santander_br o atendimento ao consumidor de vocês é péssimo, dá pra melhorar e muito!'
  - '@santander_br vocês precisam melhorar o atendimento de vocês, vou continuar a lembra-los disso até que melhorem'
  - '@santander_br estou muito insatisfeito com o serviço que vocês prestam'
  - '@santander_br demorar dezenas de minutos para ser atendimento no disk santander é um absurdo!'
  - '@santander_br a URA de vocês é péssima! Por várias vezes não funciona como deveria, vocês deveriam melhora-la!'
  - '@santander_br o serviço/atendimento de vocês é tão ruim que me faz querer fechar minha conta do Santander!'
  - '@santander_br quando vocês vão tomar vergonha e prestar um serviço de qualidade aos seus clientes?'
  - 'Se você está pensando em abrir uma conta no Santander Brasil (@santander_br), pesquise antes aqui no Twitter'
  - '@santander_br nenhum canal de atendimento de vocês funciona! Vou avisar pra todo mundo nunca comprar nada com vocês'
  - 'Ficava me perguntando se só eu que tenho problemas com @santander_br mas foi só pesquisar aqui no Twitter q ficou claro que não'
  - 'Não aguento mais o @santander_br, nunca mais quero ter conta/comprar nada deles #boicote'
  - 'Eu já fui mal atendido na vida, mas o @santander_br está de parabéns. É um novo nível de péssimo atendimento'
  - 'Depois de ser cliente do @santander_br voltei a acreditar em karma. Que atendimento péssimo!'
  - '@santander_br por um serviço tão caro vocês deveriam cuidar melhor dos seus clientes'
  - 'Toda vez que entro em contato com o SAC do @santander_br me sinto como se estivesse pedindo um favor. Não aguento mais!'
  - 'Nunca coloquei empresa nenhuma na justiça mas o @santander_br está me fazendo mudar de ideia'
  - 'Acorda @santander_br, o antendimento de vocês é horrível!'
  - '@santander_br responder um tweet dias depois não é \"fazer atendimento em mídias sociais\" não, é fingimento'
  - 'Quer uma dica? Não se torne cliente do @santander_br #ficadica'
  - 'Passando aqui só pra dizer que ainda odeio o @santander_br'
  - 'Mais um dia e nada mudou em relação ao atendimento do @santander_br, continua péssimo'
  - 'Viajar e precisar falar com o @santander_br é o jeito mais rápido de estragar uma viagem'
  - 'Incrível como mesmo fazendo o mesmo tipo de compra todo mês, o @santander_br ainda bloqueia meu cartão'
  - 'O que falta pro @santander_br entender que o meu perfil de compra e parar de bloquear o meu cartão?'
  - 'Mesmo com acesso a todos os meus dados de conta, o @santander_br não consegue resolver o bloqueio do meu cartão'
  - '@santander_br como uma empresa deste tamanho tem um atendimento por telefone tão ruim?!'
  - 'Seu dia tá bom? Experimente ligar pro @santander_br e ver se você n vai do céu pro inferno rapidinho'
  - 'Quer uma dica? Não abra conta no @santander_br, sério!'
  - 'Serviço no Brasil é sempre ruim, mas o do @santander_br consegue ser o pior'
  - 'Precisa ligar pro @santander_br pra resolver algo? Se prepare pra esperar 20 minutos pra ser atendido'
  - 'Aquela promessa de resolver tudo pelo app do @santander_br é só promessa mesmo...'
google_analytics:
